[package]
content = {type = "Playable"}
id = "atomic_fps"
name = "atomic_fps"
version = "0.0.1"

[dependencies]
base_assets = {deployment = "1TGOiCi2XmuXsY7jwnJpWg"}
character_animation = {deployment = "1OUhMOxUgCWmwpPGicFOfc"}
fps_controller = {deployment = "4qcnuQpcxcMDogPdNsKl6s"}
