[package]
id = "dinamo"
name = "dinamo"
version = "0.0.1"
content = { type = "Playable" }
ambient_version = "0.3.0-nightly-2023-09-18"

[dependencies]
orbit_camera = { deployment = "D6ezUylONCqJeP6yzcvj0" }